### ISSUE TITLE
aquamonitR R package

### ISSUE THREAD

**Issue by RaoulWolf** [NIVANorge/aquamonitR#5] opened 2021-01-07 09:53 UTC
Hi all,

a basic R package implementation of aquamonitR is live on my fork: https://github.com/RaoulWolf/aquamonitR

The package dependencies are reduced and the package *now* automatically chooses the test host; this of course will need to change. 

All user-facing functions are available when loading the package, while non-user-facing functions (which now start with a dot in front, e.g., `.get_json()`) are hidden from users; they need to be called explicitly with `:::` if users want to use them directly.

I was a bit (a lot) out of my depth with the `.query()` function, especially with the deep assignments (e.g., `<<-`); looks like voodoo to me, but it somehow works. I'm not really familiar with this type of functional coding, but could there be an easier way of coding this? 😅 

Anyway, please let me know if the package works as intended 😃

**Comment by JamesSample** [comment] 2021-01-07 10:24
Really nice work - thanks @RaoulWolf ! You've done a _much_ better job of packaging it up than I would have done, so your help is much appreciated :-)

All tested and works for me. Perhaps you could try too @DagHjermann, using `remotes::install_github("NIVANorge/aquamonitR")` ? 

> I was a bit (a lot) out of my depth with the .query() function, especially with the deep assignments (e.g., <<-); looks like voodoo to me [...]

I don't fully understand these assignments either! Actually, this is the first class I've ever written in R, and until a few weeks ago I'd never seen the `<<-` operator before. My code is essentially "cargo cult" programming based on [this](https://stackoverflow.com/a/11562457/505698) StackOverflow post, but (miraculously) it does seem to work as intended and it's sufficiently similar to Roar's Python implementation that I think it should be maintainable, even if there are better ways. Maybe one day I'll find time to get my head around all the different class types in R...

Now merged to `NIVANorge/aquamonitR` and closed by 926abba475da9d88c346f106f08d1d37cc4c353a.

Thanks all for your input :-)

**Closed as completed by JamesSample** 2021-01-07 10:24 UTC

**Comment by DagHjermann** [comment] 2021-01-07 11:55
Hmm, using install_github didn't work, see below. I will do some research on this later....
> `> remotes::install_github("NIVANorge/aquamonitR")`
> Using github PAT from envvar GITHUB_PAT
> Error: Failed to install 'unknown package' from GitHub:
>   HTTP error 404.
>   No commit found for the ref master
> 
>   Did you spell the repo owner (`NIVANorge`) and repo name (`aquamonitR`) correctly?
>   If spelling is correct, check that you have the required permissions to access the repo.  
>  
> `> remotes::install_github("RaoulWolf/aquamonitR")`
> Using github PAT from envvar GITHUB_PAT
> Error: Failed to install 'unknown package' from GitHub:
>   HTTP error 404.
>   No commit found for the ref master
> 
>   Did you spell the repo owner (`RaoulWolf`) and repo name (`aquamonitR`) correctly?
>   If spelling is correct, check that you have the required permissions to access the repo.

Regarding `<<-`, I think it is assignement to the global environmnent. E.g., if you write `x <<- 42` in a function, x will be assigned to 42 not only inside the function but also outside. Often discouraged (because functional programming) but sometimes it's just necessary..... So the old saying, "functions are like Las Vegas, everything that happens there stays there" doesn't count if you use `<<-`.... ;-)

**Comment by JamesSample** [comment] 2021-01-07 12:30
Yep, `<<-` is the "scoping operator". In this case, _I think_ it's being used to distinguish between class attributes and instance attributes, but the effect is to make certain attributes "globally" available to other methods within the class.

The `HTTP error 404` you're seeing is weird, @DagHjermann. I think it's basically saying your PC can't find the repository webpage. Are you sure there's nothing weird going on with your internet connection?

**Comment by RaoulWolf** [comment] 2021-01-07 13:51
I just ran `remotes::install_github("NIVANorge/aquamonitR")` and `remotes::install_github("RaoulWolf/aquamonitR")` on my machine and it worked?! 

... but I recently had troubles with Github access from RStudio because of the authentication. I had to setup a new SSH RSA key **and** make sure git uses SSH *via* the console trick explained [here](https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url#switching-remote-urls-from-https-to-ssh). 

Or maybe it's something entirely else ;)

**Comment by DagHjermann** [comment] 2021-01-10 07:55
I researched this a bit, before I got the brilliant idea to update remotes.... and guess what, that worked.
